package main

// file generated by
// github.com/mh-cbon/goriller
// do not edit

import (
	"github.com/gorilla/mux"
)

// ControllerGorillerRPC is a goriller of *ControllerHTTPGen.
// ControllerHTTPGen is an httper of *ControllerJSONGen.
// ControllerJSONGen is jsoner of *Controller.
// Controller of some resources.
type ControllerGorillerRPC struct {
	embed *ControllerHTTPGen
}

// NewControllerGorillerRPC constructs a goriller of *ControllerHTTPGen
func NewControllerGorillerRPC(embed *ControllerHTTPGen) *ControllerGorillerRPC {
	ret := &ControllerGorillerRPC{
		embed: embed,
	}
	return ret
}

// Bind the given router.
func (t ControllerGorillerRPC) Bind(router *mux.Router) {
	router.HandleFunc("GetByID", t.embed.GetByID)
	router.HandleFunc("UpdateByID", t.embed.UpdateByID)
	router.HandleFunc("DeleteByID", t.embed.DeleteByID)
	router.HandleFunc("TestVars1", t.embed.TestVars1)
	router.HandleFunc("TestCookier", t.embed.TestCookier)
	router.HandleFunc("TestSessionner", t.embed.TestSessionner)
	router.HandleFunc("TestRPCer", t.embed.TestRPCer)

}
