package main

// file generated by
// github.com/mh-cbon/jsoner
// do not edit

import (
	"bytes"
	"encoding/json"
	"github.com/mh-cbon/httper/lib"
	jsoner "github.com/mh-cbon/jsoner/lib"
	"io"
	"net/http"
)

// ControllerJSONGen is jsoner of *Controller.
// Controller of some resources.
type ControllerJSONGen struct {
	embed     *Controller
	finalizer jsoner.Finalizer
}

// NewControllerJSONGen constructs a jsoner of *Controller
func NewControllerJSONGen(embed *Controller, finalizer jsoner.Finalizer) *ControllerJSONGen {
	if finalizer == nil {
		finalizer = &jsoner.JSONFinalizer{}
	}
	ret := &ControllerJSONGen{
		embed:     embed,
		finalizer: finalizer,
	}
	return ret
}

//UnmarshalJSON JSON unserializes ControllerJSONGen
func (t *ControllerJSONGen) UnmarshalJSON(b []byte) error {
	var embed *Controller
	if err := json.Unmarshal(b, &embed); err != nil {
		return err
	}
	t.embed = embed
	return nil
}

//MarshalJSON JSON serializes ControllerJSONGen
func (t *ControllerJSONGen) MarshalJSON() ([]byte, error) {
	return json.Marshal(t.embed)
}

// GetByID Decodes reqBody as json to invoke *Controller.GetByID.
// Other parameters are passed straight
// GetByID ...
// @route /{id}
// @methods GET
func (t *ControllerJSONGen) GetByID(urlID int) (io.Reader, error) {

	ret := new(bytes.Buffer)
	var retErr error

	retVar0 := t.embed.GetByID(urlID)

	out, encErr := json.Marshal([]interface{}{retVar0})
	if encErr != nil {
		retErr = encErr
	} else {
		var b bytes.Buffer
		b.Write(out)
		ret = &b
	}

	return ret, retErr

}

// UpdateByID Decodes reqBody as json to invoke *Controller.UpdateByID.
// Other parameters are passed straight
// UpdateByID ...
// @route /{id}
// @methods PUT,POST
func (t *ControllerJSONGen) UpdateByID(urlID int, reqBody io.Reader) (io.Reader, error) {

	ret := new(bytes.Buffer)
	var retErr error

	var decBody *Tomate
	decErr := json.NewDecoder(reqBody).Decode(decBody)
	if decErr != nil {
		return nil, decErr
	}
	retVar1 := t.embed.UpdateByID(urlID, decBody)

	out, encErr := json.Marshal([]interface{}{retVar1})
	if encErr != nil {
		retErr = encErr
	} else {
		var b bytes.Buffer
		b.Write(out)
		ret = &b
	}

	return ret, retErr

}

// DeleteByID Decodes reqBody as json to invoke *Controller.DeleteByID.
// Other parameters are passed straight
// DeleteByID ...
// @route /{id}
// @methods DELETE
func (t *ControllerJSONGen) DeleteByID(REQid int) (io.Reader, error) {

	ret := new(bytes.Buffer)
	var retErr error

	retVar2 := t.embed.DeleteByID(REQid)

	out, encErr := json.Marshal([]interface{}{retVar2})
	if encErr != nil {
		retErr = encErr
	} else {
		var b bytes.Buffer
		b.Write(out)
		ret = &b
	}

	return ret, retErr

}

// TestVars1 Decodes reqBody as json to invoke *Controller.TestVars1.
// Other parameters are passed straight
// TestVars1 ...
func (t *ControllerJSONGen) TestVars1(w http.ResponseWriter, r *http.Request) (io.Reader, error) {

	ret := new(bytes.Buffer)
	var retErr error

	t.embed.TestVars1(w, r)

	return ret, retErr

}

// TestCookier Decodes reqBody as json to invoke *Controller.TestCookier.
// Other parameters are passed straight
// TestCookier ...
func (t *ControllerJSONGen) TestCookier(c httper.Cookier) (io.Reader, error) {

	ret := new(bytes.Buffer)
	var retErr error

	t.embed.TestCookier(c)

	return ret, retErr

}

// TestSessionner Decodes reqBody as json to invoke *Controller.TestSessionner.
// Other parameters are passed straight
// TestSessionner ...
func (t *ControllerJSONGen) TestSessionner(s httper.Sessionner) (io.Reader, error) {

	ret := new(bytes.Buffer)
	var retErr error

	t.embed.TestSessionner(s)

	return ret, retErr

}

// TestRPCer Decodes r as json to invoke *Controller.TestRPCer.
// TestRPCer ...
func (t *ControllerJSONGen) TestRPCer(r *http.Request) (io.Reader, error) {

	ret := new(bytes.Buffer)
	var retErr error
	input := struct {
		Arg0 int
	}{}
	decErr := json.NewDecoder(r.Body).Decode(&input)
	if decErr != nil {
		return nil, decErr
	}

	retVar3 := t.embed.TestRPCer(input.Arg0)

	output := struct {
		Arg0 bool
	}{
		Arg0: retVar3,
	}

	outBytes, encErr := json.Marshal(output)
	if encErr != nil {
		retErr = encErr
	} else {
		var b bytes.Buffer
		b.Write(outBytes)
		ret = &b
	}

	return ret, retErr

}
