package main

// file generated by
// github.com/mh-cbon/goriller
// do not edit

import (
	"github.com/gorilla/mux"
)

// ControllerGoriller is a goriller of *ControllerHTTPGen.
// ControllerHTTPGen is an httper of *ControllerJSONGen.
// ControllerJSONGen is jsoner of *Controller.
// Controller of some resources.
type ControllerGoriller struct {
	embed *ControllerHTTPGen
}

// NewControllerGoriller constructs a goriller of *ControllerHTTPGen
func NewControllerGoriller(embed *ControllerHTTPGen) *ControllerGoriller {
	ret := &ControllerGoriller{
		embed: embed,
	}
	return ret
}

// Bind the given router.
func (t ControllerGoriller) Bind(router *mux.Router) {
	router.HandleFunc("/{id}", t.embed.GetByID).Methods("GET")
	router.HandleFunc("/{id}", t.embed.UpdateByID).Methods("PUT", "POST")
	router.HandleFunc("/{id}", t.embed.DeleteByID).Methods("DELETE")

}
