package main

// file generated by
// github.com/mh-cbon/goriller
// do not edit

import (
	"github.com/gorilla/mux"
	"strings"
)

var xxStringsSplit = strings.Split

// GorillerTomate is a goriller of *HTTPController.
// HTTPController is an httper of *JSONController.
// JSONController is jsoner of *Controller.
// Controller of some resources.
type GorillerTomate struct {
	embed *HTTPController
	r     *mux.Router
}

// NewGorillerTomate constructs a goriller of *HTTPController
func NewGorillerTomate(embed *HTTPController, r *mux.Router) *GorillerTomate {
	ret := &GorillerTomate{
		embed: embed,
		r:     r,
	}
	return ret
}

// Make the given router.
func (t GorillerTomate) Bind(router *mux.Router) {

	router.HandleFunc("/{id}", t.embed.GetByID).Methods("GET")
	router.HandleFunc("/{id}", t.embed.UpdateByID).Methods("PUT", "POST")
	router.HandleFunc("/{id}", t.embed.DeleteByID).Methods("DELETE")

}
